### ISSUE TITLE
issue with extintion

### ISSUE THREAD

**Issue by izeinnn** [coolsonu39/coursera-subtitle-ext#4]
The extension doesn't work at all!

**Comment by VeigarJia** [comment]
> The extension doesn't work at all!

you need to refresh your page after install this extension

**Comment by izeinnn** [comment]
it's not working. It only turns off the subtitles, but not back on.

**Comment by NakerTheFirst** [comment]
> The extension doesn't work at all!

You can copy-paste the code from #3 or #2 PRs that fix this issue.

**Comment by izeinnn** [comment]
Working now.
